version: '3'
services:
  ddns:
    build: .
    restart: always
    environment:
      RECORD_TTL: 60
      ZONE: example.org
      SHARED_SECRET: changeme
    ports:
      - "53:53"
      - "53:53/udp"
      - "8080:8080"
#    volumes:
#       - ./bind-data:/var/cache/bind
